language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules
script:
  - yarn run release
deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY} # Add your personal API token as an environment variable in Travis
  file: "release.zip"
  skip_cleanup: true
  on:
    tags: true
